
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: VUmeter
*
* preset name: OLED
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/
#ifndef IMAGE_VUmeter_H_
#define IMAGE_VUmeter_H_

#include <stdint.h>



typedef struct {
	const uint8_t *data;
	uint16_t width;
	uint16_t height;
	uint8_t dataSize;
} tImage;

extern const tImage VUmeterBG;

#endif /* IMAGE_VUmeter_H_ */
